### ISSUE TITLE
build base rbase-metrics with action

### ISSUE THREAD

**Issue by ewelinawilkosz** [verifa/tempoR#21]
build and publish - so no one else has to waste time on building it

**Comment by mike-vainio-verifa** [comment]
# #20 
Seems to work, only problem is that it built an AMD64 image when I need ARM64... fml

**Comment by mike-vainio-verifa** [comment]
Added the cross-platform builds but it still doesn't run on M1, I guess R just doesn't work there. No need for it to work on my laptop anyhow, I have other machines.
